sudo: false
language: elixir
elixir:
  - 1.9
otp_release:
  - 22.0
cache:
  directories:
    - _build
    - deps
install:
  - mix local.hex --force
  - mix local.rebar --force
  - mix deps.get
script:
  - mix test
before_deploy:
  - mix compile
deploy:
  skip_cleanup: true
  provider: script
  script: mix hex.publish --yes
  on:
    tags: true
